# This file is a template, adjusted by wesley

workflow:
  name: 'pipeline branch: $CI_COMMIT_BRANCH  commit hash: $CI_COMMIT_SHA'

variables:
  JACOCO_CSV_LOCATION: "domain/build/customJacocoReportDir/test/jacocoTestReport.csv"

stages:          # List of stages for jobs, and their order of execution
  - build
  - coverage
  - test
  - jacocoTestCoverageVerification

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: gradle
  script:
    - gradle build
    - echo "Compile complete."

frontend-build:
  stage: build
  image: node:latest
  script:
        - cd client
        - npm install
        - npm run build
        - npm version patch
  artifacts:
      paths:
        - "client/"
      name: '$CI_JOB_NAME'

coverage-job:
  stage: coverage
  image: gradle
  script: 
    - gradle test 
    - gradle jacocoTestReport
    - awk -F "," '{instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_CSV_LOCATION
  when: always
  coverage: '/([0-9]{1,3}.[0-9]*).%.covered/'

jacocoTestCoverageVerification:
    violationRules:
        rule:
            limit:
                minimum: 0.95
