export const About = () => {
return <div >
<article >
    <h1 data-cy="headerAbout">Welcome to the information page</h1>
    <p>
      
        This site is generated by Wesley Mols as part of the individual project @Sogyo The Netherlands.
        This is the final project of the Sogyo academy for software engineers.
<b> My project is titled IPsportdata.</b> This application can take Maximal Lactate Steady State (MLSS) test data and return an estimaiton for anearobe threshold power. The goal is to analyse test results and give a race power advice (not yet implemented). Users should first perform a cycling test as described in the following protocol.
<h2>On the home page you can find the MLSS analysis</h2>
A protocol to find MLSS must be followed similar to the protocol on: https://www.highnorth.co.uk/articles/blood-lactate-testing-protocols-for-cyclists
It is recommended to perform this test on an ergometer and have some practice in taking lactate samples. 
Sample values can be entered in the specific boxes.<br/>
This results in the following business rules:<br/>
*  power data n corresponds with sample 1 and sample 2<br/>
*  if sample 2 - sample 1 is smaller than 1 then next input is expected, else a return statement shows power n and power n-1. <br/>
*  aerobe threshold is calculated by multiplying MLSS with 72%. <br/>
*  power to weight ratio is calculated on MLSS devided by the weight (watt/kg). <br/>

    </p>
    
    <h2>
    Information about the user input fields for MLSS analysis
    </h2>
    <p>
      You must enter a username which is stored in the database to retrieve your data. <br/>
    You may enter your weigth. Please enter a number with up to 2 decimals inidcated by a dot. This way your watt/kg value for your FTP is calculated. <br/>
    We are working on the implementation of a calculator that estimates your cycling speed based on size. However, entering your length does not do anything yet. Please enter a whole number. 
    Please enter your data one row at the time, filling in all the boxes on the second row. <br/>
    Please enter power as a whole number. <br/>
    Please enter lactate as a decimal. <br/>
    Please enter heart rate as a whole number. <br/>
    </p>
</article>
<br/><br/>
<article>
  <h2>Information about the ramptest page</h2>
  <p>
    A incremental ramp test is recommended to be completed in a controlled environment with some assistence for data measuring and monitoring the athletes wellbeing. <br/>
    Upon completion you can enter your speed or power numbers with the corresponding heart rate in the input fields. <br/>
    To do so please submit each data point seperately via the button. After two inputs the "create plot" button can be clicked, which will generate a line graph connecting the data points.<br/>
    (this is functionality is still in progress)
  </p>
</article>

</div>
}