export const About = () => {
return <div >
<article >
    <h1>Welcome to the information page</h1>
    <p>
        This site is generated by Wesley Mols as part of the individual project @Sogyo The Netherlands.
        This is the final project of the Sogyo academy for software engineers.
My project is titled IPsportdata. This application can take Maximal Lactate Steady State (MLSS) test data and return an estimaiton for anearobe threshold power. The goal is to analyse test results and give a race power advice. Users should first perform a cycling test as described in the following protocol.

A protocol to find MLSS must be followed similar to the described protocol on: https://www.highnorth.co.uk/articles/blood-lactate-testing-protocols-for-cyclists
It is recommended to perform this test on an ergometer and have some practice in taking lactate samples. 
Sample values can be entered in the specific boxes.
This results in the following business rules:
One power data n corresponds with sample 1 and sample 2
Two. if sample 2 - sample 1 is smaller than 1 then next input is expected, else a return statement shows power n and power n-1
    </p>
</article>

</div>
}